

answers <- list("what_is_true" = c("TRUE",
                                   "FALSE",
                                   "10",
                                   "\"hello\"",
                                   "NULL",
                                   "NA",
                                   "2",
                                   "0",
                                   "3",
                                   "1",
                                   "2",
                                   "TRUE",
                                   "FALSE"),
                "on_vectors" = c("x",
                                 "y",
                                 "1,2,3",
                                 '"1","2","3"',
                                 "123",
                                 "y",
                                 "x",
                                 "x",
                                 "2",
                                 '"2", "3"',
                                 '"1","3"',
                                 '"a","b","c"'),
                "on_calculations" = as.character(c(2,0, 90,256, 40000,
                                                   0, 1,  0, 200, 4,
                                                   7.389056,  3, 100, 7, 8,
                                                   3, 1, 0,  -1, 3.142, 3.14)),
                "single_bracket_vector_subsetting" = c('"j"', '"letter_20"', 'c("a", "j", "t")',
                                                       'c("letter_7","letter_14","letter_21")',
                                                       'x', '"q"', '"c", "e", "a"', 
                                                       '"a", "b", "c", "d", "e"', '"a", "g", "m", "s", "y"',
                                                       '"letter_17"', '17', 'c("c", "b", "a")',
                                                       '21', 'c(22, 23, 24, 25, 26)', 'c(1, 2, 3, 4)',
                                                       'c("a", "b", "c", "d")', 'c(1, 2, 25, 26)',
                                                       'c(12,14,16,18,20,22,24,26)'),
                "everything_is_a_function" = c("1+2", '"function"', "1:10", 
                                               '"function"', "1:10 %% 2", '"function"', 
                                               '"r" %in% letters', "x[5]"),
                "on_lists" = c('"character"', '"list"','"list"', '1','"2", TRUE', '"numeric"',
                               '"character"', '"logical"','1', '"2"','"subscript out of bounds"', 
                               '"x", "y", "z"','"number", "string", "boolean"', '12','TRUE',
                               '210','3', '3', '3', '4','"numeric"', '14',
                               'number = 1, string = "2", boolean = TRUE, x = 12, y = 6, z = 24'))





