

answers <- list("what_is_true" = c("TRUE",
                                    "FALSE",
                                    "10",
                                    "\"hello\"",
                                    "NULL",
                                    "NA",
                                    "2",
                                    "0",
                                    "3",
                                    "1",
                                    "2",
                                    "TRUE",
                                    "FALSE"),
                "on_vectors" = c("x",
                                 "y",
                                 "1,2,3",
                                 '"1","2","3"',
                                 "123",
                                 "y",
                                 "x",
                                 "x",
                                 "2",
                                 '"2", "3"',
                                 '"1","3"',
                                 '"a","b","c"'))